allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false
minimumReleaseAge: 4320
overrides:
  extract-zip@<=2.0.1: 2.0.1
  serialize-javascript@<=7.0.2: 7.1.0
  serialize-javascript@>=5.0.0 <7.0.5: 7.1.1
