export const sel = {
  trackList: "#track-list",
  trackRow: ".track-row",
  trackRowById: (id: number) => `[data-track-id="${id}"]`,
  searchInput: "#search-input",
  libraryTab: (label: string) => `[role="tab"][aria-selected]*=${label}`,
  sortHeader: (label: string) => `button[role="columnheader"]*=${label}`,
  settingsButton: "#btn-settings",
  scanButton: "#btn-scan-now",
  scanStatusBar: "#scan-status-bar",
  closeSettings: "#btn-close-settings",
  playlist: "#playlist",
  playlistRow: ".playlist-row",
  clearPlaylist: "#btn-clear-playlist",
  autoPlaylistToggle: "#btn-generate",
  btnPlay: "#btn-play",
  btnStop: "#btn-stop",
  btnNext: "#btn-next",
  btnPrev: "#btn-prev",
  timeDisplay: ".time-pill",
  editButton: ".btn-edit",
  contextMenu: "#context-menu",
  // Scope this from the menu element: WebdriverIO's `*=` text selectors accept
  // only a tag with one class/id/attribute, never a descendant combinator.
  contextMenuItem: (label: string) => `button[role="menuitem"]*=${label}`,
  // "Editor" in this codebase means metadata and nothing else; playback markers
  // are cue points (#279), with their own dialog.
  metadataDialog: "#metadata-dialog",
  metadataTitle: "#metadata-title",
  metadataArtist: "#metadata-artist",
  metadataAlbum: "#metadata-album",
  metadataGenre: "#metadata-genre",
  metadataYear: "#metadata-year",
  metadataError: "#metadata-error",
  metadataSave: "#btn-metadata-save",
  metadataCancel: "#btn-metadata-cancel",
  cuePointDialog: "#cue-point-dialog",
  cuePointField: (marker: string) => `#cue-field-${marker}`,
  cuePointSave: "#btn-cue-points-save",
  cuePointClose: "#btn-cue-points-close",
} as const;
