export const sel = {
  trackList: "#track-list",
  trackRow: ".track-row",
  trackRowById: (id: number) => `[data-track-id="${id}"]`,
  searchInput: "#search-input",
  libraryTab: (label: string) => `[role="tab"][aria-selected]*=${label}`,
  sortHeader: (label: string) => `button[role="columnheader"]*=${label}`,
  settingsButton: "#btn-settings",
  scanButton: "#btn-scan-now",
  scanStatusBar: "#scan-status-bar",
  closeSettings: "#btn-close-settings",
  playlist: "#playlist",
  playlistRow: ".playlist-row",
  clearPlaylist: "#btn-clear-playlist",
  autoPlaylistToggle: "#btn-generate",
  btnPlay: "#btn-play",
  btnStop: "#btn-stop",
  btnNext: "#btn-next",
  btnPrev: "#btn-prev",
  timeDisplay: ".time-pill",
  editButton: ".btn-edit",
  contextMenu: "#context-menu",
  // Scope this from the menu element: WebdriverIO's `*=` text selectors accept
  // only a tag with one class/id/attribute, never a descendant combinator.
  contextMenuItem: (label: string) => `button[role="menuitem"]*=${label}`,
  editorDialog: "#editor-dialog",
  editorTitle: "#editor-title",
  editorArtist: "#editor-artist",
  editorAlbum: "#editor-album",
  editorGenre: "#editor-genre",
  editorYear: "#editor-year",
  editorError: "#editor-error",
  editorSave: "#btn-editor-save",
  editorCancel: "#btn-editor-cancel",
} as const;
